bus/urls.py
from django.conf.urls import url
from . import views

app_name = 'bus'
urlpatterns=[
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<line_id>[0-9]+)/$', views.detail, name='detail'),
]

c9_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^bus/',include('bus.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns=[
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote, name='vote'),
]

bus/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Line(models.Model):
    text_dep = models.CharField(max_length=100,default="")
    text_arr = models.CharField(max_length=100,default="")
    city_dep = models.CharField(max_length=10)
    city_arr = models.CharField(max_length=10)
    rinko_dep = models.CharField(max_length=10)
    rinko_arr = models.CharField(max_length=10)
    def __str__(self):
        return str(self.id) + ':' + self.text_dep+" to "+self.text_arr
    def __unicode__(self):
        return str(self.id) + ':' + self.text_dep+" to "+self.text_arr

polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

bus/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse
from django.views import generic
import django.utils.encoding  
import urllib2
import busparser

from .models import Line

class IndexView(generic.ListView):
    '''インデックスページ
    バスの乗り場+行き先パターンをデータベースから拾ってきてリスト表示する
    '''
    template_name = 'bus/index.html'
    context_object_name='line_list'
    def get_queryset(self):
        """バスの乗り場+行き先パターンをデータベースから拾ってきてリスト表示する"""
        return Line.objects.all()

def detail(request, line_id):
    '''個別の時刻表示ページ
    DBから市バス、臨港バス用のパラメータ値を持ってきて各ページから情報を取る
    取得したHTMLを解析して一覧を作成、ソートして表示する
    '''
    # DBから情報取ってくる
    line = get_object_or_404(Line, pk=line_id)

    # 各社サイトのURL編集
    url_city=r"http://www.kcbn.jp/loca/depArr/DepArrDspStatus.asp?ID=2011051019230470&DepKey={dep}&ArrKey={arr}".format(dep=line.city_dep,arr=line.city_arr)
    url_rinko=r"http://www.rinkobus-navi.jp/blsys/loca?VID=lsc&EID=nt&DSMK={dep}&ASMK={arr}".format(dep=line.rinko_dep,arr=line.rinko_arr)

    # 各社サイトから情報取得
    result_city=urllib2.urlopen(url_city)
    result_rinko=urllib2.urlopen(url_rinko)
    
    # 取得したHTMLの解析
    parser_city=busparser.CityParser()
    parser_rinko=busparser.RinkoParser()
    parser_city.feed(unicode(result_city.read(),'cp932'))
    parser_rinko.feed(unicode(result_rinko.read(),'cp932'))
    
    # マージとソート
    mergelist = parser_city.getlist() + parser_rinko.getlist()
    sortedlist=sorted(mergelist,key=lambda x:x['prediction'])

    return render(request,'bus/detail.html',{
        'buslist':sortedlist,
        'url_city':url_city,
        'url_rinko':url_rinko,
        'text_dep':line.text_dep,
        'text_arr':line.text_arr,
    })

polls/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice,Question

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name='latest_question_list'
    
    def get_queryset(self):
        """return the last five published questions"""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

'''
def index(request):
    latest_question_list=Question.objects.order_by('pub_date')[:5]
    context={
        'latest_question_list':latest_question_list,
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,'polls/detail.html', {'question':question})
    
def results(request,question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request,'polls/results.html',{'question':question})
'''

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print selected_choice
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',{
            'question':question,
            'error_message': "You didin't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))
    

bus/templates/bus/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="X-UA-Compatible" content="IE-egde" /> 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  {% block title %}{% endblock %}

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- JQuery Mobile hosts-->
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css">
  <!-- link rel="stylesheet" type="text/css" href="{% static 'bus/style.css' %}" / -->
</head>

<body>

  <div class="container">
    <div class="main">
      {% block contents %}{% endblock %}
    </div>
  </div>
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>
</body>

</html>

bus/templates/bus/detail.html
{% extends "bus/base.html" %} {% block title %}
<title>{{text_dep}}/{{text_arr}}</title>
{% endblock title %} {% block contents %}
<div class="panel panel-primary">
    <div class="panel-heading" id="title">{{ text_dep }}<span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>{{ text_arr }}</span>
    </div>

    <table id="timetable" class="table table-striped ui-responsive table-stroke" data-role="table" data-mode="columntoggle">
        <thead id="tableHeader">
            <tr>
                <th>系統</th>
                <th>予測</th>
                <th>定刻</th>
                <th>状況</th>
                <th data-priority="2">乗り場</th>
                <th data-priority="3">行き先</th>
                <th data-priority="4">車両</th>
                <th data-priority="2">到着</th>
                <th data-priority="3">運行</th>
            </tr>
        </thead>
        <tbody id="tableBody">
            {% for row in buslist %}
            <tr>
                <td>
                    {% if row.operator == "臨港" %}
                    <span class="label label-danger">{{row.route}}</span> {% else %}
                    <span class="label label-info">{{row.route}}</span> {% endif %}
                </td>
                <td><strong>{{row.prediction}}</strong></td>
                <td>{{row.timetable}}</td>
                <td>{{row.situation}}</td>
                <td>{{row.gate}}</td>
                <td>{{row.destination}}</td>
                <td>{{row.vihicle}}</td>
                <td>{{row.arrival}}</td>
                <td>
                    {% if row.operator == "臨港" %}
                    <span class="label label-danger">{{row.operator}}</span> {% else %}
                    <span class="label label-info">{{row.operator}}</span> {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="panel panel-footer">
        <a href="../">
            <span class="label label-primary">戻る</span>
        </a>
        <a href={{url_city}} target="*">
            <span class="label label-info">川崎市バスナビ</span>
        </a>
        <a href={{url_rinko}} target="*">
            <span class="label label-danger">臨港バスナビ</span>
        </a>
    </div>
</div>
{% endblock contents %}

bus/templates/bus/index.html
{% extends "bus/base.html" %} {% block title %}
<title>bus stop by Django</title>
{% endblock title %} {% block contents %}
<div class="panel panel-primary">
    <div class="panel-heading">バス到着予測</div>
    {% if line_list %} {% for line in line_list %}
    <div class="panel-body">
        <a href="{% url 'bus:detail' line.id %}">
            {{ line.text_dep }}
            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
            {{ line.text_arr }}</a></li>
    </div>
    {% endfor %} {% else %}
    <p>No polls are available.</p>
    {%endif%}
</div>
{% endblock contents %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>Starter Template for Bootstrap</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="http://getbootstrap.com/examples/starter-template/starter-template.css" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="#">Project name</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    {% block contents %}{% endblock %}
  </div>
  <!-- /.container -->


  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>
    window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
  </script>
  <script src="../../dist/js/bootstrap.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>

</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load static %}

{% block contents %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} 
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{forloop.counter}}">
        {{ choice.choice_text }}
    </label><br/> {% endfor %}
    <input type="submit" value="Vote" />
</form>
<hr/>
<div id="gridtest">
    <div class="row">
                <div class="col-md-2 col-xs-4">col-md-2</div>    
                <div class="col-md-2 col-xs-4">col-md-2</div>    
                <div class="col-md-2 col-xs-4">col-md-2</div>    
                <div class="col-md-3 col-xs-6">col-md-3</div>    
                <div class="col-md-3 col-xs-6">col-md-3</div>    
    </div>
</div>
{% endblock contents %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load static %}

{% block contents %}
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {%endif%}
{% endblock contents %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{choice.votes|pluralize }}</li>
{% endfor %}    
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>